---
- name: Install mlocate on Ubuntu and RPi/Orange Pi
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache (only for Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install locate
      package:
        name: locate
        state: present
